language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "pypy3"
install:
  - pip3 install .
before_script:
  - pip3 install coverage
  - pip3 install coveralls
script:
  - coverage run --source fqfa -m unittest
after_success:
  - coveralls
